#!/bin/bash
INSTALL_ROOT=$(dirname "$0")

MOUNTS="/proc /dev /sys /tmp /run /var"

die() {
  echo "Error: $@"
  exit 1
}

run_in_cros() {
  grep cros /proc/cmdline 2>&1 1>/dev/null
  [ $? -eq 0 ]
}

mount_chroot() {
  local d
  for d in ${MOUNTS}; do
    mount -n --bind "${d}" "./${d}"
    mount --make-slave "./${d}"
  done
}

cleanup() {
  local d
  for d in ${MOUNTS}; do
    umount -lf "./${d}" || :
  done
}

main() {
  if run_in_cros; then
    die "The command can only running in Yocto or Ubuntu."
  fi
	cd "${INSTALL_ROOT}/.." || exit 1
  mount_chroot
  chroot . /usr/sbin/chromeos-firmwareupdate
  cleanup
  if [ $? -ne 0 ]; then
    die "Failed to update uboot and env"
  fi
  if [ -f /boot/u-boot.bin-rtd1619b_emmc.bak ]; then
    rm /boot/u-boot.bin-rtd1619b_emmc.bak
  fi
  mv /boot/u-boot.bin-rtd1619b_emmc /boot/u-boot.bin-rtd1619b_emmc.bak
  cp ./boot/u-boot.bin-rtd1619b_emmc /boot
  sync
  read -n 1 -p "Press Any key to reboot to Chromium OS"
  reboot
}

main $@
