#!/bin/bash
INSTALL_ROOT=$(dirname "$0")

die() {
  echo "Error: $@"
  exit 1
}

run_in_cros() {
  grep cros /proc/cmdline 2>&1 1>/dev/null
  [ $? -eq 0 ]
}

main() {
  if run_in_cros; then
    die "The command can only running in Yocto or Ubuntu."
  fi
	cd "${INSTALL_ROOT}" || exit 1
  ../usr/sbin/chromeos-firmwareupdate
  if [ $? -ne 0 ]; then
    die "Failed to update uboot and env"
  fi
  mv /boot/u-boot.bin-rtd1619b_emmc /boot/u-boot.bin-rtd1619b_emmc.bak
  cp ../boot/u-boot.bin-rtd1619b_emmc /boot
  sync
  read -n 1 -p "Press Any key to reboot to Chromium OS"
  reboot
}

main $@
